//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace PushNotificationServer.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("30")]
        public int CheckUpdateEveryMins {
            get {
                return ((int)(this["CheckUpdateEveryMins"]));
            }
            set {
                this["CheckUpdateEveryMins"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public DateTime LastUpdatedNews {
            get {
                return ((DateTime)(this["LastUpdatedNews"]));
            }
            set {
                this["LastUpdatedNews"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool NewsAutoUpdate {
            get {
                return ((bool)(this["NewsAutoUpdate"]));
            }
            set {
                this["NewsAutoUpdate"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public DateTime LastUpdatedHotNews {
            get {
                return ((DateTime)(this["LastUpdatedHotNews"]));
            }
            set {
                this["LastUpdatedHotNews"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        public DateTime DBUpdateTime {
            get {
                return ((DateTime)(this["DBUpdateTime"]));
            }
            set {
                this["DBUpdateTime"] = value;
            }
        }
    }
}
